from tasks.task1 import Task1
from tasks.task2 import Task2
from tasks.task3 import Task3
from tasks.task4 import Task4
from tasks.task5 import Task5
from tasks.task6 import Task6
from tasks.task7 import Task7
from tasks.task8 import Task8
from tasks.task9 import Task9
from tasks.task10 import Task10
from tasks.task11 import Task11
from tasks.task12 import Task12
from tasks.task13 import Task13
from tasks.task14 import Task14
from tasks.task15 import Task15
from tasks.task16 import Task16
